# Generated by Django 5.1 on 2024-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='unique_person_id',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
