# Generated by Django 5.1 on 2024-08-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0002_customusermodel_unique_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='unique_person_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
