# Generated by Django 5.1 on 2024-08-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLPAPIAPP', '0004_quizmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Enter your question')),
                ('question_type', models.CharField(choices=[('mcq', 'Normal'), ('true/false', 'TRUE/FALSE'), ('msq', 'multiple-choice')], max_length=50, verbose_name="What's type of your question")),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OLPAPIAPP.quizmodel')),
            ],
        ),
    ]
