# Generated by Django 5.1 on 2024-08-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLPAPIAPP', '0007_resultmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='OLPAPIAPP.questionmodel'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='OLPAPIAPP.quizmodel'),
        ),
    ]
